{% set name = "pymde" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymde-{{ version }}.tar.gz
  sha256: e18d822b735cdd61b710057c4e08c49fd534fb90484a53ab151b0ea6cf3d4d6a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools >=18.0
    - numpy
  run:
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pynndescent
    - python
    - scipy
    - pytorch
    - torchvision
    - requests

test:
  imports:
    - pymde
    - pymde.functions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cvxgrp/pymde
  summary: Minimum-Distortion Embedding
  description: |
    PyMDE is a Python library for computing vector embeddings for finite sets of
    items, such as images, biological cells, nodes in a network, or any other
    abstract object.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
    - akshayka
